### ISSUE TITLE
[Meetup] Mocha: dulces pruebas con javascript

### ISSUE THREAD

**Issue by pandres95** [IbagueJS/organization#1]
Se ha propuesat realizar una charla para finales del mes de abril, de tal manera que tenemos suficiente tiempo para organizarla y difundirla. Aquí va entonces mi propuesta

# Mocha: dulces pruebas con javascript
Mocha es un framework de test unitarios para javascript, con excelentes features para automatizar pruebas tanto en entornos de servidor como en browsers o aplicaciones de escritorio/móviles que utilicen javascript.

En este meetup, demostraremos las cualidades básicas que le dan un buen cuerpo a un desarrollo, y exploraremos los sabores que pueden acompañarlo, a través de pequeños ejemplos.

## Cosas por definir:
- [X] Fecha
- [x] Lugar
- [x] Hora
- [x] Tematica

**Comment by Gioyik** [comment]
He actualizado el issue con las cosas necesitamos definir para el encuentro. 

La tematica me parece bien. Mi voto es :+1:

**Comment by YeisonTapia** [comment]
excelente temática, muy interesante.

**Comment by pandres95** [comment]
## Propuestas fecha
1. Jueves, 23 de abril de 2015
2. Martes, 27 de abril de 2015

**Comment by pandres95** [comment]
@Gioyik ¿de qué se tratará su charla?

**Comment by Gioyik** [comment]
Vamos a dejar por ahora de a una sola charla por meetup. Luego ya veremos.
